# external imports
from pydantic import BaseModel
from typing import Optional
from uuid import UUID4
from datetime import datetime

# Authenticated User Model
class AuthenticatedUser(BaseModel):
    success: bool
    user_id: Optional[str] = None
    organization_id: Optional[str] = None

class Organization(BaseModel):
    id: Optional[UUID4] = None  # Auto-generated
    name: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

# API Key Model
class APIKey(BaseModel):
    id: Optional[UUID4] = None  # Auto-generated
    user_id: UUID4
    organization_id: UUID4
    key: str
    created_at: Optional[datetime] = None
    last_used: Optional[datetime] = None
    usage_count: Optional[int] = 0

# User Organization Model
class UserOrganization(BaseModel):
    user_id: UUID4
    organization_id: UUID4
    role: Optional[str] = "member"  # Default role is 'member'
    created_at: Optional[datetime] = None  # Auto-generated by Supabase

    class Config:
        from_attributes = True  # Ensures compatibility with ORM results